spring.application.name=AuditService
notification.exchange.name=notification.exchange
audit.exchange.name=audit.exchange

email.service.queue.name=email.queue
sms.service.queue.name=sms.queue
audit.service.queue.name=audit.queue

audit.routing.key=audit.log.key

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root

spring.datasource.url=jdbc:postgresql://postgres:5432/audit_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8081
