spring.application.name=RegistrationService
notification.exchange.name=notification.exchange
audit.exchange.name=audit.exchange

email.service.queue.name=email.queue
sms.service.queue.name=sms.queue
audit.service.queue.name=audit.queue

audit.routing.key=audit.log.key

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root

server.port=8080

audit.service.url=http://audit-service:8081
